export const GET_NOTES_REQUEST = "GET_NOTES_REQUEST" ; 
export const GET_NOTE_REQUEST = "GET_NOTE_REQUEST" ; 
export const UPDATE_NOTES_REQUEST = "UPDATE_NOTES_REQUEST" ; 
export const DELETE_NOTE_REQUEST =  "DELETE_NOTE_REQUEST" ; 